import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillInstagram, AiFillLinkedin, AiFillGithub, AiFillMediumCircle } from 'react-icons/ai';
import { useState } from 'react';
import Script from 'next/script'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
      <Head>
        <meta charset="utf-8" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>afatih</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon" />

        <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-M3GSJ4C910" />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-M3GSJ4C910', {
            page_path: window.location.pathname,
          });
        `,
          }}
        />

      </Head>

      <main className={darkMode ? "dark" : ""} >
        <section className="min-h-screen bg-white px-10 text-black dark:text-gray-200 dark:bg-gray-900">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-2xl font-segoe font-medium">afatih</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" /></li>
            </ul>
          </nav>
          <div className="pt-10 pr-10 pl-10">
            <h2 className="text-4xl">Ahmet Fatih Ay</h2>
            <h3 className="text-xl pb-5">Developer and Student.</h3>
            <p className="text-md text-gray-800 dark:text-gray-400">Part-time full stack web developer at Allianz Türkiye. I am interested in cloud computing and trying to improve myself in this regard.</p>
          </div>
          <div className="pl-10 pt-5 text-4xl flex justify-start gap-3 p">
            <a href="https://github.com/ahmetfatihay" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/afay/" target="_blank" >
              <AiFillLinkedin />
            </a>
            <a href="https://www.instagram.com/a.fatihay/" target="_blank">
              <AiFillInstagram />
            </a>
            <a href="https://medium.com/@imaay" target="_blank">
              <AiFillMediumCircle />
            </a>
          </div>
        </section>
      </main>
    </>
  )
}
